default_context:
  project_name: 'tokidoki'
  project_slug: 'tokidoki'
  domain_main: 'ryo-aws-practice.net'
  domain_staging: 'dev.ryo-aws-practice.net'
  docker_swarm_stack_name_main: 'ryo-aws-practice-net'
  docker_swarm_stack_name_staging: 'dev-ryo-aws-practice-net'
  secret_key: 'te8q1(=jxy6!@0i_x=-fa&x74_g6*vlpd^%72mp*q!nea*_hu#'
  first_superuser: 'admin@ryo-aws-practice.net'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ryo-aws-practice.net", "https://dev.ryo-aws-practice.net", "https://ryo-aws-practice.net", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'ryo.development0320@gmail.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@ryo-aws-practice.net'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'ryo-aws-practice.net'
  traefik_constraint_tag_staging: 'dev.ryo-aws-practice.net'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
